"""mkdocs hook: generate the Reference pages and the Changelog from code.

D-0.10-13: the reference cannot drift. mkdocs calls `on_files`, which adds
one generated page for each entry of `build_pages`. Tests call
`build_pages` directly, so they do not need mkdocs installed.
"""
from __future__ import annotations

import argparse
import importlib.util
import inspect
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_PAGES = (
    "reference/cli.md", "reference/gates.md", "reference/config.md",
    "reference/findings.md", "reference/hooks.md",
    "reference/file-formats.md", "changelog.md",
)
NOTE = ("<!-- Generated by docs/hooks/reference.py at build time. "
        "Change the code, not this page. -->\n")
ARG_HEADER = ["Argument", "Required", "Default", "Choices", "Help"]


def _cell(value) -> str:
    return " ".join(str(value).split()).replace("|", "\\|")


def _table(header: list, rows: list) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return "\n".join(out) + "\n"


def _page(title: str, *parts: str) -> str:
    return "\n".join([f"# {title}\n", NOTE, *parts]).rstrip() + "\n"


# ------------------------------------------------------------------ CLI
def _subparser_action(parser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def iter_commands(parser, prefix="harness"):
    """Yield (full name, help, subparser) for each subcommand, depth first."""
    action = _subparser_action(parser)
    if action is None:
        return
    helps = {a.dest: a.help or "" for a in action._choices_actions}
    for name, child in action.choices.items():
        full = f"{prefix} {name}"
        yield full, helps.get(name, ""), child
        yield from iter_commands(child, full)


def _help(action) -> str:
    if not action.help or action.help == argparse.SUPPRESS:
        return ""
    try:
        return action.help % {"default": action.default, "prog": ""}
    except (KeyError, TypeError, ValueError):
        return action.help


def _arguments(parser) -> list:
    rows = []
    for a in parser._actions:
        if isinstance(a, (argparse._HelpAction, argparse._SubParsersAction)):
            continue
        name = ", ".join(a.option_strings) or a.dest
        default = a.default
        if default in (None, False, [], argparse.SUPPRESS):
            default = ""
        choices = ", ".join(map(str, a.choices)) if a.choices else ""
        rows.append([f"`{name}`", "yes" if a.required else "no",
                     default, choices, _help(a)])
    return rows


def render_cli(parser) -> str:
    parts = [_cell(parser.description or "") + "\n",
             "## Global options\n", _table(ARG_HEADER, _arguments(parser))]
    for full, help_text, child in iter_commands(parser):
        level = "#" * min(full.count(" ") + 1, 4)
        parts.append(f"{level} `{full}`\n")
        if help_text:
            parts.append(_cell(_help_text(help_text)) + "\n")
        parts.append("```text\n" + child.format_usage().strip() + "\n```\n")
        rows = _arguments(child)
        if rows:
            parts.append(_table(ARG_HEADER, rows))
    return _page("CLI reference", *parts)


def _help_text(text: str) -> str:
    try:
        return text % {}
    except (KeyError, TypeError, ValueError):
        return text


# ---------------------------------------------------------------- gates
def render_gates(gates) -> str:
    parts = ["Each builtin gate is one module in `engine/gates/`. "
             "This page shows each module's docstring and its `GATE` "
             "declaration.\n"]
    for gate in gates:
        decl = gate.GATE
        doc = inspect.getdoc(gate) or ""
        title, _, body = doc.partition("\n")
        parts.append(f"## {decl['id']}\n")
        parts.append(f"**{_cell(title)}**\n")
        if body.strip():
            parts.append(body.strip() + "\n")
        rows = [[f"`{key}`",
                 ", ".join(map(str, value))
                 if isinstance(value, (list, tuple)) else value]
                for key, value in decl.items()]
        parts.append(_table(["Key", "Value"], rows))
    parts.append("A repo adds its own gates with `gates.extra`. See "
                 "[Repo-local gates](../extending/extra-gates.md).\n")
    return _page("Gates", *parts)


# --------------------------------------------------------------- config
def _flatten(d: dict, prefix: str = ""):
    for key, value in d.items():
        if isinstance(value, dict) and value:
            yield from _flatten(value, f"{prefix}{key}.")
        else:
            yield f"{prefix}{key}", value


def render_config(default_config: dict, template_text: str) -> str:
    rows = [[f"`{key}`", f"`{json.dumps(value)}`"]
            for key, value in _flatten(default_config)]
    return _page(
        "Config keys",
        "`.harness/config.yaml` holds the config of one repo. The engine "
        "merges it over the defaults below.\n",
        "The keys `acceptance.*`, `landing.*`, `gates.extra` and "
        "`gates.degraded_mode` have no entry in the defaults. They appear "
        "only in the annotated template below.\n",
        "## Defaults\n", _table(["Key", "Default"], rows),
        "## Annotated template\n",
        "`harness init` writes this file. `{{languages}}` becomes the "
        "languages that init detects.\n",
        "```yaml\n" + template_text.rstrip() + "\n```\n")


# ------------------------------------------------------------- findings
def render_findings(catalog: dict) -> str:
    rows = [[f"`{code}`", text] for code, text in sorted(catalog.items())]
    return _page(
        "Finding codes",
        "Each finding has a code. `harness gates explain <CODE>` prints "
        "the same text as this table.\n",
        _table(["Code", "Explanation"], rows))


# ---------------------------------------------------------------- hooks
def render_hooks(hooks_json: dict, event_map: dict, engine_events) -> str:
    rows = []
    for host_event, entries in hooks_json["hooks"].items():
        for entry in entries:
            target = event_map.get(host_event)
            rows.append([f"`{host_event}`", entry.get("matcher", "all"),
                         f"`{target}`" if target else "adapter only"])
    events = "\n".join(f"- `{name}`" for name in engine_events)
    return _page(
        "Hook events",
        "`hooks/hooks.json` wires Claude Code hooks to `hooks/adapter.py`. "
        "The adapter turns each hook into one engine event.\n",
        "## Claude Code hooks\n",
        _table(["Host hook", "Matcher", "Engine event"], rows),
        "## Engine events\n", events + "\n")


# --------------------------------------------------------- file formats
def render_formats(schemas: dict, prose: str) -> str:
    parts = [prose.strip() + "\n", "## Validated row schemas\n",
             "`harness verify` and `harness doctor` check these files "
             "row by row.\n"]
    for filename, spec in schemas.items():
        parts.append(f"### `.harness/{filename}`\n")
        parts.append(f"Id field: `{spec['id_field']}`.\n")
        rows = [[f"`{field}`", typ.__name__, "yes" if required else "no",
                 ", ".join(spec["enums"].get(field, ()))]
                for field, typ, required in spec["fields"]]
        parts.append(_table(["Field", "Type", "Required", "Allowed"], rows))
    return _page("File formats", *parts)


# ---------------------------------------------------------------- build
def _load_adapter(root: Path):
    spec = importlib.util.spec_from_file_location(
        "harness_docs_adapter", root / "hooks" / "adapter.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build_pages(root: Path) -> dict:
    """Render every generated page. Any failure raises: no empty page."""
    root = Path(root)
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    from engine import DEFAULT_CONFIG
    from engine.cli import build_parser
    from engine.events import EVENTS
    from engine.findings import CATALOG
    from engine.gates import builtin_gates
    from engine.schema import SCHEMAS

    adapter = _load_adapter(root)
    hooks_json = json.loads((root / "hooks" / "hooks.json").read_text())
    return {
        "reference/cli.md": render_cli(build_parser()),
        "reference/gates.md": render_gates(builtin_gates()),
        "reference/config.md": render_config(
            DEFAULT_CONFIG, (root / "templates" / "harness.yaml").read_text()),
        "reference/findings.md": render_findings(CATALOG),
        "reference/hooks.md": render_hooks(hooks_json, adapter.EVENT_MAP,
                                           EVENTS),
        "reference/file-formats.md": render_formats(
            SCHEMAS, (root / "docs" / "hooks" / "file-formats.md").read_text()),
        "changelog.md": (root / "CHANGELOG.md").read_text(),
    }


def on_files(files, config):
    """mkdocs hook: add the generated pages; refuse a hand-written copy."""
    from mkdocs.exceptions import PluginError
    from mkdocs.structure.files import File

    for src_uri, content in build_pages(REPO_ROOT).items():
        if files.get_file_from_path(src_uri) is not None:
            raise PluginError(
                f"docs/{src_uri} is generated by docs/hooks/reference.py. "
                f"Delete the hand-written file.")
        files.append(File.generated(config, src_uri, content=content))
    return files
