"""`harness init` — scaffold (or migrate) a repo's substrate; `harness
upgrade` — bring a substrate scaffolded by an older plugin up to this one.

Also owns the autonomy profile writer (`init --autonomy` and `start` both
pre-approve the slice loop's command surface through it) and the engine
vendoring that makes the scaffolded CI workflow self-contained.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from engine import ENGINE_VERSION, SCHEMA_VERSION, HarnessError
from engine.cli.common import (PLUGIN_ROOT, _dep_status, _install_merge_drivers,
                               _print)

# where `init` vendors the engine inside the substrate: the scaffolded CI
# workflow runs this copy, so a consumer repo verifies with nothing but its
# own tree (no clone of the plugin repo, no HARNESS_REPO variable)
VENDOR_DIR = Path(".harness") / "engine"
WORKFLOW_PATH = Path(".github") / "workflows" / "harness-verify.yml"
# first line of the scaffolded workflow: the marker that says "harness wrote
# this" and therefore that `upgrade` may refresh it
WORKFLOW_MARKER = "# harness verify — CI enforcement"


# ------------------------------------------------------------------ init
LANG_HINTS = {".py": "python", ".ts": "typescript", ".tsx": "typescript",
              ".rs": "rust", ".go": "go",
              ".yaml": "yaml", ".yml": "yaml", ".tf": "hcl", ".hcl": "hcl"}


PROVENANCE_RULE = (
    "The provenance rule: authored files are written by humans (or "
    "human-approved architect sessions) and never regenerated; derived files "
    "are regenerated by hooks and hand-editing one is a bug. If you can't "
    "tell which a file is, that's a design defect — flag it in review.")


def cmd_init(args):
    root = Path(args.root or os.getcwd()).resolve()
    hdir = root / ".harness"
    templates = PLUGIN_ROOT / "templates"

    # dependency preflight — surface missing deps NOW, not at the first Stop
    missing = sorted(k for k, v in _dep_status().items() if v == "MISSING")
    if missing:
        print(f"warning: engine dependencies missing: {', '.join(missing)}\n"
              f"  extraction will degrade to degenerate shadows until you run:\n"
              f"  pip install {' '.join(missing)}", file=sys.stderr)

    if hdir.exists() and not args.migrate:
        if args.autonomy:
            # substrate already scaffolded: just add the autonomy profile
            _write_autonomy_settings(root)
            return 0
        print(f"error: {hdir} already exists; refusing to overwrite an existing "
              f"substrate without --migrate", file=sys.stderr)
        return 1
    if hdir.exists() and args.migrate:
        # `init --migrate` is the historical upgrade entry point; it does
        # exactly what `upgrade` does
        return cmd_upgrade(args)

    hdir.mkdir(parents=True)
    (hdir / "memory" / "session").mkdir(parents=True)
    (hdir / "shadows").mkdir()

    # detect languages -> enable packs (relative parts: an ignored name in
    # the ABSOLUTE path — repo under ~/venv, a worktree — must not blank it)
    from engine import IGNORED_DIRS
    detected = {v: False for v in ("python", "typescript", "rust", "go",
                                   "yaml", "hcl")}
    for p in root.rglob("*"):
        if any(part in IGNORED_DIRS for part in p.relative_to(root).parts):
            continue
        lang = LANG_HINTS.get(p.suffix.lower())
        if lang:
            detected[lang] = True
    if not any(detected.values()):
        detected = {k: True for k in detected}

    cfg = (templates / "harness.yaml").read_text()
    langs = "\n".join(f"  {k}: {str(v).lower()}" for k, v in sorted(detected.items()))
    cfg = cfg.replace("{{languages}}", langs)
    (hdir / "config.yaml").write_text(cfg)
    (hdir / "schema_version").write_text(f"{SCHEMA_VERSION}\n")
    # registry ships the planned standard-abstraction slots; decisions and
    # backlog start EMPTY. The author-gate's domain-coverage check already
    # blocks until every registry domain has a real decision row — seeding
    # EDIT-ME placeholder rows was redundant with that guarantee, read as
    # defects on a fresh init, and (for backlog) invited exactly the
    # hand-editing the backlog skill forbids.
    shutil.copy(templates / "registry.seed.jsonl", hdir / "registry.jsonl")
    for empty in ("decisions.jsonl", "backlog.jsonl", "edges.jsonl",
                  "telemetry.jsonl", "boundaries.jsonl", "notes.jsonl",
                  "memory/durable.jsonl"):
        (hdir / empty).touch()

    (root / "adr").mkdir(exist_ok=True)
    shutil.copy(templates / "adr.md", root / "adr" / "000-template.md")
    (root / "contracts").mkdir(exist_ok=True)
    if not any((root / "contracts").glob("*.yaml")):
        shutil.copy(templates / "contract.stub.yaml", root / "contracts" / "api.yaml")
    _write_workflow(root)
    _vendor_engine(root)

    gi = root / ".gitignore"
    lines = gi.read_text().splitlines() if gi.exists() else []
    for entry in (".harness/sidecar.db", ".harness/sidecar.db-*",
                  ".harness/memory/session/", ".worktrees/",
                  ".claude/settings.local.json",
                  "__pycache__/", "*.pyc", ".pytest_cache/"):
        if entry not in lines:
            lines.append(entry)
    gi.write_text("\n".join(lines) + "\n")

    # agent-facing repo docs: AGENTS.md (cross-tool standard) + CLAUDE.md
    # (Claude Code reads it; imports AGENTS.md to avoid content drift).
    # Authored the moment they land — never overwrite existing ones.
    agents_md = root / "AGENTS.md"
    if not agents_md.exists():
        shutil.copy(templates / "agents-md.md", agents_md)
    else:
        print("note: AGENTS.md already exists — not touched; consider adding "
              "the harness workflow section from templates/agents-md.md")
    claude_md = root / "CLAUDE.md"
    if not claude_md.exists():
        claude_md.write_text(
            "# CLAUDE.md\n\n"
            "This repo is harness-enforced. The agent working agreement lives "
            "in AGENTS.md (imported below) — slices, gates, provenance, and "
            "the substrate-first workflow.\n\n"
            "@AGENTS.md\n")
    else:
        print("note: CLAUDE.md already exists — not touched; consider adding "
              "'@AGENTS.md' so agents load the harness working agreement")

    # bare `pytest` must SEE acceptance tests: the NNN_*.py convention is
    # invisible to pytest's default python_files under directory collection
    # (the engine always passes explicit paths, but a human's bare run
    # silently skipping the whole suite is a hidden trap). Only written when
    # the project has no pytest config of its own.
    has_pytest_cfg = any((root / n).exists()
                         for n in ("pytest.ini", "tox.ini", "setup.cfg"))
    if not has_pytest_cfg and not (
            (root / "pyproject.toml").exists()
            and "[tool.pytest" in (root / "pyproject.toml").read_text()):
        (root / "pytest.ini").write_text(
            "# harness: make NNN_*.py acceptance tests collectable by bare\n"
            "# pytest (the engine passes explicit paths and is unaffected)\n"
            "[pytest]\n"
            "python_files = test_*.py *_test.py [0-9]*_*.py\n")
    else:
        print("note: existing pytest config found — ensure python_files "
              "includes the [0-9]*_*.py acceptance-test pattern, or bare "
              "pytest will skip tests/slices/")

    _install_merge_drivers(root)

    # git DX: make harness notes discoverable, and warn about empty repos
    # (worktree-per-slice needs at least one commit to branch from)
    import subprocess
    if (root / ".git").exists():
        subprocess.run(["git", "-C", str(root), "config",
                        "notes.displayRef", "refs/notes/harness"],
                       capture_output=True)
        has_commit = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True).returncode == 0
        if not has_commit:
            print("note: repo has no commits yet — commit the scaffolded "
                  "substrate before /harness:build (worktrees branch from a "
                  "commit): git add -A && git commit -m 'harness substrate'")

    if args.autonomy:
        _write_autonomy_settings(root)

    print(f"substrate scaffolded at {hdir} (schema {SCHEMA_VERSION}); "
          f"languages: {sorted(k for k, v in detected.items() if v)}")
    print(PROVENANCE_RULE)
    return 0


# ------------------------------------------------------------------ vendor
def _vendor_engine(root) -> dict:
    """Copy the engine (`bin/harness` + `engine/`) into `.harness/engine/`.

    The scaffolded workflow runs `.harness/engine/bin/harness verify`, so CI
    needs nothing from the plugin repo — no clone, no `HARNESS_REPO`
    variable, no token for a private engine repo. The copy is replaced
    wholesale (never merged) so a module the plugin deleted cannot linger,
    and never carries caches. `.harness/` is an ignored dir for extraction,
    so the vendored .py files are not project source to the consumer's own
    gates.

    Args:
        root: Substrate root.

    Returns:
        `{"path", "version", "action", "from"}` — action is `installed`,
        `refreshed` (was another version, or damaged) or `unchanged`.
    """
    target = root / VENDOR_DIR
    version_file = target / "VERSION"
    previous = (version_file.read_text().strip()
                if version_file.exists() else None)
    if previous == ENGINE_VERSION and _vendored_matches(target):
        return {"path": str(VENDOR_DIR), "version": ENGINE_VERSION,
                "action": "unchanged", "from": previous}
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    ignore = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache")
    shutil.copytree(PLUGIN_ROOT / "engine", target / "engine", ignore=ignore)
    (target / "bin").mkdir()
    shutil.copy(PLUGIN_ROOT / "bin" / "harness", target / "bin" / "harness")
    (target / "bin" / "harness").chmod(0o755)
    version_file.write_text(f"{ENGINE_VERSION}\n")
    (target / "README.md").write_text(
        "# vendored harness engine\n\nDerived: written by `harness init` / "
        "`harness upgrade`, run by `.github/workflows/harness-verify.yml`. "
        "Never hand-edit; `harness upgrade` replaces it wholesale after a "
        "plugin upgrade.\n")
    return {"path": str(VENDOR_DIR), "version": ENGINE_VERSION,
            "action": "installed" if previous is None else "refreshed",
            "from": previous}


def _vendored_matches(target) -> bool:
    """True when every engine file in the plugin has an identical vendored
    copy and nothing extra sits in the vendored tree (a stale module the
    plugin deleted, a hand edit). Caches are ignored on both sides."""
    from engine import sha256_file

    def _files(base):
        out = {}
        for p in base.rglob("*"):
            if p.is_dir() or "__pycache__" in p.parts or p.suffix == ".pyc":
                continue
            out[p.relative_to(base)] = sha256_file(p)
        return out

    if not (target / "bin" / "harness").exists():
        return False
    if sha256_file(target / "bin" / "harness") != \
            sha256_file(PLUGIN_ROOT / "bin" / "harness"):
        return False
    return _files(PLUGIN_ROOT / "engine") == _files(target / "engine")


def vendored_engine_status(root) -> dict:
    """What `doctor --substrate` reports about the vendored engine.

    Args:
        root: Substrate root.

    Returns:
        `{"status", "version", "engine_version", "path"}` with status one of
        `self-hosted` (this is the plugin repo: the engine lives at its
        root), `current`, `stale` (another version, or drifted) or
        `missing` (scaffolded by a plugin that predates vendoring).
    """
    root = Path(root).resolve()
    target = root / VENDOR_DIR
    report = {"path": str(VENDOR_DIR), "engine_version": ENGINE_VERSION,
              "version": None}
    if root == PLUGIN_ROOT:
        report["status"] = "self-hosted"
        return report
    version_file = target / "VERSION"
    if not version_file.exists():
        report["status"] = "missing"
        return report
    report["version"] = version_file.read_text().strip()
    ok = report["version"] == ENGINE_VERSION and _vendored_matches(target)
    report["status"] = "current" if ok else "stale"
    return report


def _write_workflow(root) -> dict:
    """Scaffold or refresh the CI workflow; never clobber a hand-authored one.

    Args:
        root: Substrate root.

    Returns:
        `{"path", "action"}` with action `written` (absent before),
        `refreshed` (harness-generated and out of date), `unchanged`, or
        `kept` (not harness-generated; a `note` names what to add by hand).
    """
    template = (PLUGIN_ROOT / "templates" / "ci-verify.yml").read_text()
    target = root / WORKFLOW_PATH
    report = {"path": str(WORKFLOW_PATH)}
    if not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(template)
        report["action"] = "written"
        return report
    current = target.read_text()
    if current == template:
        report["action"] = "unchanged"
        return report
    if not current.startswith(WORKFLOW_MARKER):
        report["action"] = "kept"
        report["note"] = (
            f"{WORKFLOW_PATH} is not the harness-generated workflow, so it "
            f"was not touched. Make its engine step run "
            f"`python3 .harness/engine/bin/harness verify` (the vendored "
            f"engine) — see templates/ci-verify.yml for the reference step.")
        return report
    target.write_text(template)
    report["action"] = "refreshed"
    return report


def cmd_upgrade(args):
    """Bring a substrate scaffolded by an older plugin up to the installed
    one: schema migration, merge drivers, the vendored engine and the CI
    workflow. Idempotent; hand-authored files are never touched."""
    from engine.migrate import migrate
    root = Path(args.root or os.getcwd()).resolve()
    if not (root / ".harness").exists():
        raise HarnessError(
            f"{root / '.harness'} does not exist — nothing to upgrade; run "
            f"`harness init` to scaffold a substrate first")
    _install_merge_drivers(root)  # existing substrates pick up W5 drivers
    report = {"schema": migrate(root),
              "vendored_engine": _vendor_engine(root),
              "workflow": _write_workflow(root),
              "engine_version": ENGINE_VERSION}
    profile = root / ".claude" / "settings.json"
    if profile.exists() and "harness autonomy profile" in profile.read_text():
        # our own profile: refresh it so new pre-approved shapes land too
        report["autonomy_profile"] = _write_autonomy_settings(root, quiet=True)
    _print(report)
    return 0


def _pr_landing_rules(text, landing) -> str:
    """Open exactly the egress a pr-mode slice needs, in the written profile.

    In `landing.mode: pr` the slice cannot finish without pushing its own
    branch and opening a PR (ADR-002 / D-011), so the blanket `git push` and
    `git fetch` denies would stop the loop dead, and the sandbox's domain
    allowlist would drop the connection anyway. Everything else that leaves
    the machine stays denied.

    Only the denies are dropped — no allow rule is added. Bash rules are
    PREFIX rules, and a prefix cannot express "this slice's own branch":
    `Bash(git push origin slice/:*)` would also open
    `git push origin slice/x:main`, and `Bash(gh pr create:*)` would open
    `--repo attacker/repo`. The harness PreToolUse hook is the only opener —
    it answers `allow` for the exact shapes D-011 names and `deny` for every
    other egress command in pr mode, so nothing rides on a coarse rule.

    Args:
        text: The substituted profile JSON.
        landing: Resolved landing config.

    Returns:
        The profile JSON, rewritten in pr mode and untouched in local mode.
    """
    if landing["mode"] != "pr":
        return text
    import json
    from engine.cli.landing import forge_hosts
    profile = json.loads(text)
    perms = profile["permissions"]
    opened = ("Bash(git push:*)", "Bash(git fetch:*)")
    perms["deny"] = [r for r in perms["deny"] if r not in opened]
    remote = landing["remote"]
    # the sandbox is the other half: a permission decision does not open a
    # socket
    domains = profile.get("sandbox", {}).get("network", {}).get(
        "allowedDomains")
    if domains is not None:
        for host in forge_hosts(remote):
            if host not in domains:
                domains.append(host)
    return json.dumps(profile, indent=2) + "\n"


def _write_autonomy_settings(root, quiet=False, local=False, config=None):
    """Pre-approve the slice loop's command surface and sandbox it, in
    .claude/settings.json. Approval prompts are redundant inside a bound
    slice — the PreToolUse hook gate-checks every edit deterministically and
    CI verify backstops it. The profile still denies anything that leaves
    the machine (git push/remote/fetch) — except, in `landing.mode: pr`, the
    slice branch push and `gh pr` that D-011 names. Returns the path
    written, or None."""
    templates = PLUGIN_ROOT / "templates"
    # local=True -> settings.local.json: the per-worktree sandbox profile is
    # MACHINE state (absolute paths into that worktree). Committing it made
    # every parallel merge an add/add conflict and would point main's
    # sandbox at a deleted worktree. settings.local.json is the canonical
    # never-committed layer, and init gitignores it.
    name = "settings.local.json" if local else "settings.json"
    target = root / ".claude" / name
    if target.exists():
        # refresh our own profile (marker in _comment); never clobber a
        # hand-authored settings file
        if "harness autonomy profile" not in target.read_text():
            if not quiet:
                print(f"note: {target} already exists and is not a harness "
                      f"profile — not touched. To enable autonomy, merge "
                      f"templates/claude-settings.json (substituting "
                      f"{{{{PROJECT_DIR}}}} with this repo's path) into it "
                      f"yourself.")
            return None
    target.parent.mkdir(parents=True, exist_ok=True)
    text = (templates / "claude-settings.json").read_text()
    # the engine rules stay path-agnostic (`*/bin/harness`, D-015): the
    # expanded plugin path is install-, version- and machine-specific, and a
    # profile that names it stops matching the moment the plugin moves.
    # the sandbox and permission scope follow the TREE this profile governs:
    # a slice worktree confines writes to itself
    text = text.replace("{{PROJECT_DIR}}", str(Path(root).resolve()))
    from engine import HarnessError, load_config
    from engine.cli.landing import landing_config
    if config is None:
        try:
            config = load_config(root)
        except HarnessError:
            config = {}          # pre-substrate init: local mode by default
    landing = landing_config(config)
    text = _pr_landing_rules(text, landing)
    target.write_text(text)
    if quiet:
        return str(target)
    push_note = ("git push and git remote stay denied"
                 if landing["mode"] != "pr" else
                 f"only `git push [-u] {landing['remote']} slice/*` and "
                 f"`gh pr create|view|checks|status` are opened (landing.mode: "
                 f"pr, D-011); every other remote command stays denied")
    print(f"autonomy profile written to {target}: acceptEdits + pre-approved "
          f"harness/pytest/git-local commands; {push_note}. The harness gates "
          f"remain the guardrail — approval prompts were never the "
          f"enforcement layer.")
    print("other hosts: install the matching profile from the plugin's "
          "adapters/ dir (codex/autonomy.toml, gemini/autonomy-policy.toml, "
          "cursor/cli-permissions.json, opencode/opencode-permissions.json; "
          "pi needs none) — see ADAPTERS.md §Autonomy profiles.")
    return str(target)
