"""`harness init` — scaffold (or migrate) a repo's substrate.

Also owns the autonomy profile writer: `init --autonomy` and `start` both
pre-approve the slice loop's command surface through it.
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

from engine import SCHEMA_VERSION
from engine.cli.common import (PLUGIN_ROOT, _dep_status, _install_merge_drivers,
                               _print)


# ------------------------------------------------------------------ init
LANG_HINTS = {".py": "python", ".ts": "typescript", ".tsx": "typescript",
              ".rs": "rust", ".go": "go",
              ".yaml": "yaml", ".yml": "yaml", ".tf": "hcl", ".hcl": "hcl"}


PROVENANCE_RULE = (
    "The provenance rule: authored files are written by humans (or "
    "human-approved architect sessions) and never regenerated; derived files "
    "are regenerated by hooks and hand-editing one is a bug. If you can't "
    "tell which a file is, that's a design defect — flag it in review.")


def cmd_init(args):
    root = Path(args.root or os.getcwd()).resolve()
    hdir = root / ".harness"
    templates = PLUGIN_ROOT / "templates"

    # dependency preflight — surface missing deps NOW, not at the first Stop
    missing = sorted(k for k, v in _dep_status().items() if v == "MISSING")
    if missing:
        print(f"warning: engine dependencies missing: {', '.join(missing)}\n"
              f"  extraction will degrade to degenerate shadows until you run:\n"
              f"  pip install {' '.join(missing)}", file=sys.stderr)

    if hdir.exists() and not args.migrate:
        if args.autonomy:
            # substrate already scaffolded: just add the autonomy profile
            _write_autonomy_settings(root)
            return 0
        print(f"error: {hdir} already exists; refusing to overwrite an existing "
              f"substrate without --migrate", file=sys.stderr)
        return 1
    if hdir.exists() and args.migrate:
        from engine.migrate import migrate
        _install_merge_drivers(root)  # existing substrates pick up W5 drivers
        _print(migrate(root))
        return 0

    hdir.mkdir(parents=True)
    (hdir / "memory" / "session").mkdir(parents=True)
    (hdir / "shadows").mkdir()

    # detect languages -> enable packs (relative parts: an ignored name in
    # the ABSOLUTE path — repo under ~/venv, a worktree — must not blank it)
    from engine import IGNORED_DIRS
    detected = {v: False for v in ("python", "typescript", "rust", "go",
                                   "yaml", "hcl")}
    for p in root.rglob("*"):
        if any(part in IGNORED_DIRS for part in p.relative_to(root).parts):
            continue
        lang = LANG_HINTS.get(p.suffix.lower())
        if lang:
            detected[lang] = True
    if not any(detected.values()):
        detected = {k: True for k in detected}

    cfg = (templates / "harness.yaml").read_text()
    langs = "\n".join(f"  {k}: {str(v).lower()}" for k, v in sorted(detected.items()))
    cfg = cfg.replace("{{languages}}", langs)
    (hdir / "config.yaml").write_text(cfg)
    (hdir / "schema_version").write_text(f"{SCHEMA_VERSION}\n")
    for name, dest in (("registry.seed.jsonl", "registry.jsonl"),
                       ("decisions.seed.jsonl", "decisions.jsonl"),
                       ("backlog.seed.jsonl", "backlog.jsonl")):
        shutil.copy(templates / name, hdir / dest)
    for empty in ("edges.jsonl", "telemetry.jsonl", "boundaries.jsonl",
                  "memory/durable.jsonl"):
        (hdir / empty).touch()

    (root / "adr").mkdir(exist_ok=True)
    shutil.copy(templates / "adr.md", root / "adr" / "000-template.md")
    (root / "contracts").mkdir(exist_ok=True)
    if not any((root / "contracts").glob("*.yaml")):
        shutil.copy(templates / "contract.stub.yaml", root / "contracts" / "api.yaml")
    wf = root / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    shutil.copy(templates / "ci-verify.yml", wf / "harness-verify.yml")

    gi = root / ".gitignore"
    lines = gi.read_text().splitlines() if gi.exists() else []
    for entry in (".harness/sidecar.db", ".harness/sidecar.db-*",
                  ".harness/memory/session/", ".worktrees/",
                  ".claude/settings.local.json",
                  "__pycache__/", "*.pyc", ".pytest_cache/"):
        if entry not in lines:
            lines.append(entry)
    gi.write_text("\n".join(lines) + "\n")

    # agent-facing repo docs: AGENTS.md (cross-tool standard) + CLAUDE.md
    # (Claude Code reads it; imports AGENTS.md to avoid content drift).
    # Authored the moment they land — never overwrite existing ones.
    agents_md = root / "AGENTS.md"
    if not agents_md.exists():
        shutil.copy(templates / "agents-md.md", agents_md)
    else:
        print("note: AGENTS.md already exists — not touched; consider adding "
              "the harness workflow section from templates/agents-md.md")
    claude_md = root / "CLAUDE.md"
    if not claude_md.exists():
        claude_md.write_text(
            "# CLAUDE.md\n\n"
            "This repo is harness-enforced. The agent working agreement lives "
            "in AGENTS.md (imported below) — slices, gates, provenance, and "
            "the substrate-first workflow.\n\n"
            "@AGENTS.md\n")
    else:
        print("note: CLAUDE.md already exists — not touched; consider adding "
              "'@AGENTS.md' so agents load the harness working agreement")

    # bare `pytest` must SEE acceptance tests: the NNN_*.py convention is
    # invisible to pytest's default python_files under directory collection
    # (the engine always passes explicit paths, but a human's bare run
    # silently skipping the whole suite is a hidden trap). Only written when
    # the project has no pytest config of its own.
    has_pytest_cfg = any((root / n).exists()
                         for n in ("pytest.ini", "tox.ini", "setup.cfg"))
    if not has_pytest_cfg and not (
            (root / "pyproject.toml").exists()
            and "[tool.pytest" in (root / "pyproject.toml").read_text()):
        (root / "pytest.ini").write_text(
            "# harness: make NNN_*.py acceptance tests collectable by bare\n"
            "# pytest (the engine passes explicit paths and is unaffected)\n"
            "[pytest]\n"
            "python_files = test_*.py *_test.py [0-9]*_*.py\n")
    else:
        print("note: existing pytest config found — ensure python_files "
              "includes the [0-9]*_*.py acceptance-test pattern, or bare "
              "pytest will skip tests/slices/")

    _install_merge_drivers(root)

    # git DX: make harness notes discoverable, and warn about empty repos
    # (worktree-per-slice needs at least one commit to branch from)
    import subprocess
    if (root / ".git").exists():
        subprocess.run(["git", "-C", str(root), "config",
                        "notes.displayRef", "refs/notes/harness"],
                       capture_output=True)
        has_commit = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True).returncode == 0
        if not has_commit:
            print("note: repo has no commits yet — commit the scaffolded "
                  "substrate before /harness:build (worktrees branch from a "
                  "commit): git add -A && git commit -m 'harness substrate'")

    if args.autonomy:
        _write_autonomy_settings(root)

    print(f"substrate scaffolded at {hdir} (schema {SCHEMA_VERSION}); "
          f"languages: {sorted(k for k, v in detected.items() if v)}")
    print(PROVENANCE_RULE)
    return 0


def _write_autonomy_settings(root, quiet=False, local=False):
    """Pre-approve the slice loop's command surface and sandbox it, in
    .claude/settings.json. Approval prompts are redundant inside a bound
    slice — the PreToolUse hook gate-checks every edit deterministically and
    CI verify backstops it. The profile still denies anything that leaves
    the machine (git push/remote/fetch). Returns the path written, or None."""
    templates = PLUGIN_ROOT / "templates"
    # local=True -> settings.local.json: the per-worktree sandbox profile is
    # MACHINE state (absolute paths into that worktree). Committing it made
    # every parallel merge an add/add conflict and would point main's
    # sandbox at a deleted worktree. settings.local.json is the canonical
    # never-committed layer, and init gitignores it.
    name = "settings.local.json" if local else "settings.json"
    target = root / ".claude" / name
    if target.exists():
        # refresh our own profile (marker in _comment); never clobber a
        # hand-authored settings file
        if "harness autonomy profile" not in target.read_text():
            if not quiet:
                print(f"note: {target} already exists and is not a harness "
                      f"profile — not touched. To enable autonomy, merge "
                      f"templates/claude-settings.json (substituting "
                      f"{{{{HARNESS_BIN}}}} with "
                      f"{PLUGIN_ROOT / 'bin' / 'harness'}) into it yourself.")
            return None
    target.parent.mkdir(parents=True, exist_ok=True)
    text = (templates / "claude-settings.json").read_text()
    text = text.replace("{{HARNESS_BIN}}", str(PLUGIN_ROOT / "bin" / "harness"))
    # the sandbox and permission scope follow the TREE this profile governs:
    # a slice worktree confines writes to itself
    text = text.replace("{{PROJECT_DIR}}", str(Path(root).resolve()))
    target.write_text(text)
    if quiet:
        return str(target)
    print(f"autonomy profile written to {target}: acceptEdits + pre-approved "
          f"harness/pytest/git-local commands; git push and git remote stay "
          f"denied. The harness gates remain the guardrail — approval prompts "
          f"were never the enforcement layer.")
    print("other hosts: install the matching profile from the plugin's "
          "adapters/ dir (codex/autonomy.toml, gemini/autonomy-policy.toml, "
          "cursor/cli-permissions.json, opencode/opencode-permissions.json; "
          "pi needs none) — see ADAPTERS.md §Autonomy profiles.")
    return str(target)
